//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7_VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookNames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookNames()
        {
            this.AllBooks = new HashSet<AllBooks>();
        }
    
        public int ID { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public string Athor { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Year { get; set; }
        public string Publishing { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllBooks> AllBooks { get; set; }
    }
}
